In [7]:
import numpy as np
import pandas as pd

In [8]:
bl_07_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2007.csv')
bl_08_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2008.csv')
bl_09_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2009.csv')
bl_10_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2010.csv')
bl_11_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2011.csv')
bl_12_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2012.csv')
bl_13_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2013.csv')
bl_14_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2014.csv')
bl_15_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2015.csv')
bl_16_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2016.csv')
bl_17_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2017.csv')
bl_18_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2018.csv')
bl_19_df = pd.read_csv('..\\..\\Consolidated Data\\English_Premiership_2019.csv')

In [9]:
current_team_list = ['Arsenal',
'Aston Villa',
'Bournemouth',
'Brighton',
'Burnley',
'Chelsea',
'Crystal Palace',
'Everton',
'Leicester',
'Liverpool',
'Man City',
'Man Utd',
'Newcastle',
'Norwich',
'Sheffield Utd',
'Southampton',
'Tottenham',
'Watford',
'West Ham',
'Wolverhampton']

In [10]:
bl_combined_df = pd.DataFrame(current_team_list, columns =['Team'])

In [11]:
bl_combined_df = bl_combined_df.merge(bl_19_df[['Team','Pos']],how='left',on='Team')

In [12]:
bl_combined_df = bl_combined_df.merge(bl_18_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_17_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_16_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_15_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_14_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_13_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_12_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_11_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_10_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_09_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_08_df[['Team','Pos']],how='left',on='Team')
bl_combined_df = bl_combined_df.merge(bl_07_df[['Team','Pos']],how='left',on='Team')

In [13]:
bl_combined_df = bl_combined_df.fillna(21)
bl_combined_df.columns = ['Team','Pos_2019','Pos_2018','Pos_2017','Pos_2016','Pos_2015','Pos_2014','Pos_2013','Pos_2012','Pos_2011','Pos_2010','Pos_2009','Pos_2008','Pos_2007']

In [14]:
bl_combined_df['Avg_Pos'] = bl_combined_df.mean(axis=1)
bl_final_df = bl_combined_df[['Team','Avg_Pos']]
bl_final_df.to_csv('..\\..\\Consolidated Data\\Premier League Average Positions.csv',index=False)

In [15]:
bl_combined_df

,Team,Pos_2019,Pos_2018,Pos_2017,Pos_2016,Pos_2015,Pos_2014,Pos_2013,Pos_2012,Pos_2011,Pos_2010,Pos_2009,Pos_2008,Pos_2007,Avg_Pos
0,Arsenal,5.0,6.0,5.0,2.0,3.0,4.0,4.0,3.0,4.0,3.0,4.0,3.0,4.0,3.846154
1,Aston Villa,21.0,21.0,21.0,20.0,17.0,15.0,15.0,16.0,9.0,6.0,6.0,6.0,11.0,14.153846
2,Bournemouth,14.0,12.0,9.0,16.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,18.461538
3,Brighton,17.0,15.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,20.230769
4,Burnley,15.0,7.0,16.0,21.0,19.0,21.0,21.0,21.0,21.0,18.0,21.0,21.0,21.0,18.692308
5,Chelsea,3.0,5.0,1.0,10.0,1.0,3.0,3.0,6.0,2.0,1.0,3.0,2.0,2.0,3.230769
6,Crystal Palace,12.0,11.0,14.0,15.0,10.0,11.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,16.923077
7,Everton,8.0,8.0,7.0,11.0,11.0,5.0,6.0,7.0,7.0,8.0,5.0,5.0,6.0,7.230769
8,Leicester,9.0,9.0,12.0,1.0,14.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,16.384615
9,Liverpool,2.0,4.0,4.0,8.0,6.0,2.0,7.0,8.0,6.0,7.0,2.0,4.0,3.0,4.846154
10,Man City,1.0,1.0,3.0,4.0,2.0,1.0,2.0,1.0,3.0,5.0,10.0,9.0,14.0,4.307692
11,Man Utd,6.0,2.0,6.0,5.0,4.0,7.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3.000000
12,Newcastle,13.0,10.0,21.0,18.0,15.0,10.0,16.0,5.0,12.0,21.0,18.0,12.0,13.0,14.153846
13,Norwich,21.0,21.0,21.0,19.0,21.0,18.0,11.0,12.0,21.0,21.0,21.0,21.0,21.0,19.153846
14,Sheffield Utd,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,18.0,20.769231
15,Southampton,16.0,17.0,8.0,6.0,7.0,8.0,14.0,21.0,21.0,21.0,21.0,21.0,21.0,15.538462
16,Tottenham,4.0,3.0,2.0,3.0,5.0,6.0,5.0,4.0,5.0,4.0,8.0,11.0,5.0,5.000000
17,Watford,11.0,14.0,17.0,13.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,20.0,18.692308
18,West Ham,10.0,13.0,11.0,7.0,12.0,13.0,10.0,21.0,20.0,17.0,9.0,10.0,15.0,12.923077
19,Wolverhampton,7.0,21.0,21.0,21.0,21.0,21.0,21.0,20.0,17.0,15.0,21.0,21.0,21.0,19.076923