In [24]:
import pandas as pd
import numpy as np

In [25]:
ranking_df = pd.read_csv('..\\Consolidated Data\\Team Rankings_corrected.csv',encoding = "utf-8")

In [26]:
ranking_df = ranking_df.drop(['Unnamed: 0'],axis=1)

In [27]:
ranking_df[ranking_df['Tier']==2]

                Team  Tier
4  Manchester United     2
5  Tottenham Hotspur     2
6    Manchester City     2
7    Atlético Madrid     2
8           Juventus     2
9          Liverpool     2

In [28]:
ranking_teams=ranking_df['Team'].unique()

In [29]:
tier1_teams = ranking_teams[0:4]

In [30]:
dataset_teams = pd.read_csv('..\\Consolidated Data\\players_20.csv')

In [31]:
dataset_teams = dataset_teams['club'].unique()

In [32]:
dataset_teams

array(['FC Barcelona', 'Juventus', 'Paris Saint-Germain',
       'Atlético Madrid', 'Real Madrid', 'Manchester City', 'Liverpool',
       'Napoli', 'Tottenham Hotspur', 'Manchester United', 'Chelsea',
       'FC Bayern München', 'Inter', 'Borussia Dortmund', 'Arsenal',
       'Valencia CF', 'Lazio', 'Milan', 'Sporting CP',
       'Olympique Lyonnais', 'RB Leipzig', 'Ajax', 'LA Galaxy',
       'Atalanta', 'RC Celta', 'Bayer 04 Leverkusen', 'Real Betis',
       'FC Porto', 'SV Werder Bremen', 'West Ham United',
       'Wolverhampton Wanderers', 'AS Saint-Étienne', 'Torino',
       'Dalian YiFang FC', 'Borussia Mönchengladbach', 'Roma',
       'Guangzhou Evergrande Taobao FC', 'SL Benfica',
       'Medipol Başakşehir FK', 'Everton', 'VfL Wolfsburg',
       'Crystal Palace', 'Getafe CF', 'Shanghai SIPG FC',
       'Eintracht Frankfurt', 'Olympique de Marseille', 'Hertha BSC',
       'RSC Anderlecht', 'Villarreal CF', 'Sampdoria', 'Leicester City',
       'AS Monaco', 'Jiangsu Suning FC', 'Los Angeles FC', 'Cagliari',
       'Sevilla FC', 'Fenerbahçe SK', 'Real Sociedad',
       'TSG 1899 Hoffenheim', 'Atlético Mineiro', 'Grêmio', 'PSV',
       'Athletic Club de Bilbao', 'Deportivo Alavés', 'Boca Juniors',
       'Lokomotiv Moscow', 'Al Nassr', 'Brescia', 'Shakhtar Donetsk',
       'Shanghai Greenland Shenhua FC', 'PFC CSKA Moscow',
       'Beijing Sinobo Guoan FC', 'Levante UD', 'Cruzeiro', 'Uruguay',
       'Montpellier HSC', 'Atlanta United', 'Watford', '1. FC Köln',
       'Bournemouth', 'Beşiktaş JK', 'Real Valladolid CF', 'Racing Club',
       'Al Hilal', 'Guangzhou R&F FC', 'Sassuolo',
       'FC Girondins de Bordeaux', 'LOSC Lille', 'Galatasaray SK',
       'Chicago Fire', 'Fluminense', 'Ecuador', 'RCD Espanyol',
       'Dinamo Zagreb', 'FC Nantes', 'River Plate', 'OGC Nice',
       'Newcastle United', 'Brighton & Hove Albion', 'Club Brugge KV',
       'FC Schalke 04', 'SD Eibar', 'DC United', 'Orlando City SC',
       'Hebei China Fortune FC', 'Tigres U.A.N.L.', 'Aston Villa',
       'Montreal Impact', 'Olympiacos CFP', 'Norwich City', 'Feyenoord',
       'Toronto FC', 'KRC Genk', 'Fiorentina', 'Spartak Moscow',
       'Dynamo Kyiv', 'SK Slavia Praha', 'Southampton', 'Burnley',
       'SC Braga', 'Russia', 'RC Strasbourg Alsace', 'Wuhan Zall',
       'Vissel Kobe', 'Portland Timbers', 'Genoa', 'Beijing Renhe FC',
       'Toulouse Football Club', 'Girona FC', 'Real Zaragoza',
       'CD Leganés', 'Shenzhen FC', 'Internacional', 'CSA - AL', 'Santos',
       '1. FSV Mainz 05', 'Stoke City', 'Udinese', 'Colombia',
       'Angers SCO', 'FC Augsburg', 'Netherlands', 'Fulham',
       'FC København', 'KAA Gent', 'SC Freiburg', 'Stade Rennais FC',
       'Club América', 'Trabzonspor', 'BSC Young Boys', 'Helsingborgs IF',
       'Kaizer Chiefs', 'Parma', 'Mexico', 'Royal Antwerp FC',
       'Tianjin TEDA FC', 'Hannover 96', 'Tianjin Quanjian FC', 'Al Ahli',
       'Bologna', 'VfB Stuttgart', 'Seattle Sounders FC', 'Godoy Cruz',
       'Sparta Praha', 'Independiente Medellín', 'Sivasspor',
       'Independiente', 'Nîmes Olympique', 'Club Tijuana', 'SPAL',
       'Monterrey', 'CD Tondela', 'Fortuna Düsseldorf',
       'Vitória Guimarães', 'AZ Alkmaar', 'Atlético de San Luis', 'PAOK',
       'Nagoya Grampus', 'Club Atlético Banfield',
       'Shandong Luneng TaiShan FC', 'New York Red Bulls',
       'FC Red Bull Salzburg', 'Sweden', 'Amiens SC', 'Hellas Verona',
       'Cruz Azul', 'Gençlerbirliği SK', '1. FC Union Berlin',
       'Standard de Liège', 'Chongqing Dangdai Lifan FC SWM Team',
       'New England Revolution', 'Club Atlético Colón', 'Celtic',
       'Club Atlas', 'Botafogo', 'En Avant de Guingamp',
       'West Bromwich Albion', 'Pachuca', 'AEK Athens', 'Portimonense SC',
       'Real Salt Lake', 'FC Utrecht', 'Sheffield United',
       "Newell's Old Boys", 'Club Atlético Talleres',
       'Philadelphia Union', 'Rosenborg BK', 'FC Basel 1893', 'Brentford',
       'Club León', 'Unión de Santa Fe', 'Deportivo de La Coruña',
       'Rangers FC', 'Turkey', 'Atiker Konyaspor', 'Granada CF',
       'Perth Glory', 'Club Atlético Lanús', 'Hamburger SV', 'Al Ittihad',
       'Santos Laguna', 'Western United FC', 'Columbus Crew SC',
       'Deportivo Toluca', 'Cardiff City', 'CA Osasuna', 'Swansea City',
       'Melbourne Victory', 'Leeds United', 'Göztepe SK', 'Hungary',
       'New York City FC', 'Bulgaria', 'Kayserispor',
       'Minnesota United FC', 'Guadalajara', 'FC Groningen', 'Paraguay',
       'Junior FC', 'Al Taawoun', 'Huddersfield Town', 'Ettifaq FC',
       'Stade de Reims', 'Rayo Vallecano', 'San Lorenzo de Almagro',
       'Bahia', 'Atlético Paranaense', 'Goiás', 'Avaí FC', 'Fortaleza',
       'Kawasaki Frontale', 'Vélez Sarsfield', 'Hull City',
       'Houston Dynamo', 'Birmingham City', 'Al Wehda',
       'Nottingham Forest', 'CD Tenerife', 'Aalborg BK',
       'Preston North End', 'Bristol City', 'Lecce',
       'Gimnasia y Esgrima La Plata', 'CD Aves', 'Viktoria Plzeň',
       '1. FC Nürnberg', 'Slovenia', 'FC Metz', 'FC Midtjylland',
       'Molde FK', 'Colo-Colo', 'RCD Mallorca', 'FC Sion', 'Wisła Kraków',
       'Denizlispor', 'Middlesbrough', 'Universidad Católica',
       'Alanyaspor', 'Moreirense FC', "Côte d'Ivoire",
       'Stade Brestois 29', 'Chievo Verona', 'Boavista FC',
       'MKE Ankaragücü', 'Sydney FC', 'Al Ain FC', 'Yeni Malatyaspor',
       'Urawa Red Diamonds', 'Querétaro', 'Sporting Kansas City',
       'Málaga CF', '1. FC Heidenheim 1846', 'Atlético Tucumán',
       'Gazişehir Gaziantep F.K.', 'Clube Sport Marítimo', 'Chapecoense',
       'Atlético Nacional', 'Vitesse', 'Australia', 'Henan Jianye FC',
       'Panathinaikos FC', 'Blackburn Rovers', 'Santa Clara', 'Cameroon',
       'Puebla FC', 'U.N.A.M.', 'SD Huesca', 'Estudiantes de La Plata',
       'Austria', 'KAS Eupen', 'LASK Linz', 'Sporting de Charleroi',
       'Daegu FC', 'Real Sporting de Gijón', 'Derby County', 'Rio Ave FC',
       'South Africa', 'Famalicão', 'Neuchâtel Xamax', 'Benevento',
       'Cádiz CF', 'AIK', 'Sheffield Wednesday', 'Empoli',
       'Colorado Rapids', 'Os Belenenses', 'Unión Magdalena',
       'Real Oviedo', 'Peru', 'Antalyaspor', 'Dijon FCO', 'SV Sandhausen',
       'Rosario Central', 'Reading', 'DSC Arminia Bielefeld', 'Malmö FF',
       'Jeonbuk Hyundai Motors', 'Frosinone', 'FC Tokyo', 'Canada',
       'Çaykur Rizespor', 'FCSB (Steaua)', 'Defensa y Justicia',
       'Monarcas Morelia', 'Club Atlético Huracán', 'Ceará Sporting Club',
       'Argentinos Juniors', 'Al Shabab', 'Legia Warszawa',
       'Shimizu S-Pulse', 'Millonarios FC', 'Lechia Gdańsk', 'Brøndby IF',
       'Albacete BP', 'FC Lorient', 'Universitatea Craiova',
       'Deportivo Cali', 'SK Rapid Wien', 'Kashima Antlers', 'Poland',
       'Elche CF', 'Club Atlético Aldosivi', 'Deportes Tolima',
       'Cúcuta Deportivo', 'Club Necaxa', 'Piast Gliwice', 'Pescara',
       'Kasimpaşa SK', 'Egypt', 'Holstein Kiel', 'Livorno',
       'Coquimbo Unido', 'UD Las Palmas', 'Górnik Zabrze', 'FC Twente',
       'Paris FC', 'Racing Club de Lens', 'VfL Bochum 1848', 'Sunderland',
       'Aberdeen', 'Heart of Midlothian', 'Romania', 'Crotone', 'Iceland',
       'CFR Cluj', 'FK Austria Wien', 'UD Almería', 'SK Brann',
       'BK Häcken', 'Al Fateh', 'CD Everton de Viña del Mar',
       'FC St. Pauli', 'Gamba Osaka', 'Yokohama F. Marinos',
       'Djurgårdens IF', 'FC Dallas', 'Sagan Tosu', 'Al Fayha', 'Chile',
       'Once Caldas', 'Atlético Bucaramanga', 'FC Cincinnati',
       'San Jose Earthquakes', 'América de Cali', 'Perugia', 'La Equidad',
       'SV Darmstadt 98', 'FC Zürich', 'SC Paderborn 07',
       'SV Zulte-Waregem', 'IFK Norrköping', 'FC Viitorul', 'Pordenone',
       'AD Alcorcón', 'Sint-Truidense VV', 'KV Kortrijk',
       'Royal Excel Mouscron', 'FC Lugano', 'Hokkaido Consadole Sapporo',
       'Spezia', 'FC Paços de Ferreira', 'Servette FC',
       'US Salernitana 1919', 'Lech Poznań', 'ESTAC Troyes',
       'Fortuna Sittard', 'KV Oostende', 'VVV-Venlo', 'KSV Cercle Brugge',
       'FC Seoul', 'Cerezo Osaka', 'Stade Malherbe Caen',
       'Universidad de Chile', 'Kalmar FF', 'KV Mechelen',
       'Deportes Iquique', 'US Cremonese', 'Bolivia', 'Valenciennes FC',
       'Ulsan Hyundai FC', 'Vegalta Sendai', 'ADO Den Haag',
       'CD Palestino', 'Cittadella', 'Vitória de Setúbal',
       'FC Nordsjælland', 'Charlton Athletic', 'Al Raed',
       'Jagiellonia Białystok', 'Odense Boldklub', 'FC Thun',
       'SG Dynamo Dresden', 'Hammarby IF', 'Central Córdoba',
       'Queens Park Rangers', ' SSV Jahn Regensburg',
       'Tiburones Rojos de Veracruz', 'Patronato', 'Virtus Entella',
       'SK Sturm Graz', 'Kilmarnock', 'Extremadura UD', 'Willem II',
       'Gil Vicente FC', 'Randers FC', 'Ascoli', 'Vancouver Whitecaps FC',
       'Millwall', 'Pohang Steelers', 'Suwon Samsung Bluewings',
       'Heracles Almelo', 'Al Hazem', 'FC Juárez', 'SC Heerenveen',
       'Dinamo Bucureşti', 'Gyeongnam FC', 'KFC Uerdingen 05',
       'PEC Zwolle', 'Al Faisaly', 'Arsenal de Sarandí',
       'FC Ingolstadt 04', 'Wolfsberger AC', 'Wigan Athletic',
       'Júbilo Iwata', 'CD Lugo', 'SpVgg Greuther Fürth', 'FC Emmen',
       'Cosenza', 'AJ Auxerre', 'Cracovia', 'FC Erzgebirge Aue',
       'Grenoble Foot 38', 'Korona Kielce', 'Alianza Petrolera',
       'CD Universidad de Concepción', 'Melbourne City FC',
       'CD Antofagasta', 'Independiente Santa Fe', 'Sanfrecce Hiroshima',
       'Damac FC', 'Chamois Niortais Football Club', 'Atlético Huila',
       'CD Numancia', 'Luton Town', 'Unión La Calera', 'Le Havre AC',
       'AS Nancy Lorraine', 'Audax Italiano', 'Hibernian', 'Barnsley',
       'Pogoń Szczecin', 'Sarpsborg 08 FF', 'Kristiansund BK',
       'FC Luzern', 'Unión Española', 'IFK Göteborg', 'Envigado FC',
       'Jeju United FC', 'Patriotas Boyacá FC', 'Peterborough United',
       'Deportivo Pasto', 'Wales', 'Clermont Foot 63', 'Northern Ireland',
       'Astra Giurgiu', 'Racing Santander', 'Pisa', 'Newcastle Jets',
       'Castellammare di Stabia', 'Rionegro Águilas', 'Vålerenga Fotball',
       "CD O'Higgins", 'AC Ajaccio', 'CF Fuenlabrada', 'VfL Osnabrück',
       'Arka Gdynia', 'FC Sochaux-Montbéliard', 'SpVgg Unterhaching',
       'Central Coast Mariners', 'SV Wehen Wiesbaden', 'Fleetwood Town',
       'Venezia FC', 'Karlsruher SC', 'Wisła Płock', 'Gangwon FC',
       'IF Elfsborg', 'Sangju Sangmu FC', 'Zagłębie Lubin', 'Abha Club',
       'Jaguares de Córdoba', 'FC Botoşani', 'Motherwell',
       'FC St. Gallen', 'Bayern München II', 'CD Mirandés',
       'St. Johnstone FC', 'Lillestrøm SK', 'Odds BK', 'SD Ponferradina',
       'Doncaster Rovers', 'Örebro SK', 'Shamrock Rovers', 'FSV Zwickau',
       '1. FC Kaiserslautern', 'Portsmouth', 'Waasland-Beveren',
       'Ipswich Town', 'Dundalk', 'CD Huachipato', 'Le Mans FC',
       'Strømsgodset IF', 'Sepsi OSK', 'Sparta Rotterdam',
       'FC Admira Wacker Mödling', 'SønderjyskE', 'Hallescher FC',
       'SKN St. Pölten', 'MSV Duisburg', 'La Berrichonne de Châteauroux',
       'FC Hansa Rostock', 'Incheon United FC', 'Shonan Bellmare',
       'Orlando Pirates', 'FK Bodø/Glimt', 'Lincoln City',
       'Brisbane Roar', 'Eintracht Braunschweig', 'Curicó Unido',
       'Falkenbergs FF', 'Venezuela', '1. FC Magdeburg', 'CD Cobresal',
       'Aarhus GF', 'Salford City', 'HJK Helsinki', 'Oxford United',
       'Hobro IK', 'Esbjerg fB', 'Bolton Wanderers', 'SV Mattersburg',
       'Rotherham United', 'SCR Altach', 'Gaz Metan Mediaş', 'Tromsø IL',
       'WSG Tirol', 'IK Sirius', 'Shrewsbury', 'Oldham Athletic',
       'Southend United', 'Blackpool', 'Coventry City', 'Adelaide United',
       'Ranheim Fotball', 'SG Sonnenhof Großaspach', 'Matsumoto Yamaga',
       'Burton Albion', 'FC Hermannstadt', 'TSV 1860 München', 'LKS Lodz',
       'FC Würzburger Kickers', 'TSV Hartberg', 'Politehnica Iaşi',
       'Wellington Phoenix', 'Milton Keynes Dons', 'Stabæk Fotball',
       'Wycombe Wanderers', 'SV Waldhof Mannheim', 'AC Horsens',
       'Scunthorpe United', 'RKC Waalwijk', 'Oita Trinita', 'St. Mirren',
       'Bristol Rovers', 'Rodez Aveyron Football', 'SV Meppen',
       'Viking FK', 'Östersunds FK', 'FK Haugesund', 'Rochdale',
       'Colchester United', 'Trapani', 'Stevenage', 'Bradford City',
       'Livingston FC', 'FC Chambly Oise', 'Mansfield Town',
       'SC Preußen Münster', 'FC Voluntari', 'Accrington Stanley',
       'Al Adalah', 'Lyngby BK', 'FC Carl Zeiss Jena', 'Viktoria Köln',
       'Tranmere Rovers', 'Silkeborg IF', 'Gillingham', 'Plymouth Argyle',
       'Chemnitzer FC', 'Mjøndalen IF', 'Walsall', 'Northampton Town',
       'Hamilton Academical FC', 'Grimsby Town', 'Exeter City',
       'Swindon Town', 'Raków Częstochowa', 'Chindia Târgovişte',
       'US Orléans Loiret Football', 'Forest Green Rovers',
       'AFC Wimbledon', 'Carlisle United', 'Morecambe', 'Port Vale',
       'Cheltenham Town', 'Academica Clinceni', 'Crawley Town',
       'Ross County FC', 'AFC Eskilstuna', 'Macclesfield Town',
       'Cork City', 'Newport County', 'Crewe Alexandra', 'Leyton Orient',
       'Cambridge United', "St. Patrick's Athletic", 'Bohemian FC',
       'India', 'Finland', 'Waterford FC', 'Derry City', 'Bury',
       'New Zealand', 'GIF Sundsvall', 'Sligo Rovers', 'Finn Harps',
       'Seongnam FC', 'UCD AFC', 'Śląsk Wrocław'], dtype=object)

In [33]:
for i in range(0,len(tier1_teams)):
    print(i)
    print(tier1_teams[i])
    for j in range(0,len(dataset_teams)):
        if (tier1_teams[i] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
Chelsea
10
Chelsea
1
FC Bayern München
11
FC Bayern München
2
FC Barcelona
0
FC Barcelona
3
Real Madrid
4
Real Madrid

In [34]:
tier2_teams = ranking_df[ranking_df['Tier']==2]

tier2_teams = tier2_teams.reset_index()

tier2_teams = tier2_teams.drop(['index'],axis=1)

In [35]:
for i in range(0,len(tier2_teams)):
    print(i)
    print(tier2_teams.iloc[i]['Team'])
    for j in range(0,len(dataset_teams)):
        if (tier2_teams.iloc[i]['Team'] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
Manchester United
9
Manchester United
1
Tottenham Hotspur
8
Tottenham Hotspur
2
Manchester City
5
Manchester City
3
Atlético Madrid
3
Atlético Madrid
4
Juventus
1
Juventus
5
Liverpool
6
Liverpool

In [36]:
tier3_teams = ranking_df[ranking_df['Tier']==3]

tier3_teams = tier3_teams.reset_index()

tier3_teams = tier3_teams.drop(['index'],axis=1)

In [37]:
for i in range(0,len(tier3_teams)):
    print(i)
    print(tier3_teams.iloc[i]['Team'])
    for j in range(0,len(dataset_teams)):
        if (tier3_teams.iloc[i]['Team'] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
Arsenal
14
Arsenal
479
Arsenal de Sarandí
1
Milan
17
Milan
2
Roma
35
Roma
381
Romania
3
AS Monaco
51
AS Monaco
4
Ajax
21
Ajax

In [38]:
tier4_teams = ranking_df[ranking_df['Tier']==4]

tier4_teams = tier4_teams.reset_index()

tier4_teams = tier4_teams.drop(['index'],axis=1)

for i in range(0,len(tier4_teams)):
    print(i)
    print(tier4_teams.iloc[i]['Team'])
    for j in range(0,len(dataset_teams)):
        if (tier4_teams.iloc[i]['Team'] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
Bayer 04 Leverkusen
25
Bayer 04 Leverkusen
1
Napoli
7
Napoli
2
Everton
39
Everton
390
CD Everton de Viña del Mar
3
Valencia CF
15
Valencia CF
4
Sevilla FC
55
Sevilla FC
5
Villarreal CF
48
Villarreal CF
6
PSV
61
PSV
7
FC Schalke 04
100
FC Schalke 04
8
Borussia Dortmund
13
Borussia Dortmund
9
Inter
12
Inter
132
Internacional

In [39]:
tier5_teams = ranking_df[ranking_df['Tier']==5]

tier5_teams = tier5_teams.reset_index()

tier5_teams = tier5_teams.drop(['index'],axis=1)

for i in range(0,len(tier5_teams)):
    print(i)
    print(tier5_teams.iloc[i]['Team'])
    for j in range(0,len(dataset_teams)):
        if (tier5_teams.iloc[i]['Team'] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
West Ham United
29
West Ham United
1
Real Sociedad
57
Real Sociedad
2
RC Celta
24
RC Celta
3
Torino
32
Torino
4
Southampton
117
Southampton
5
Aston Villa
106
Aston Villa
6
Hertha BSC
46
Hertha BSC
7
TSG 1899 Hoffenheim
58
TSG 1899 Hoffenheim
8
Real Betis
26
Real Betis
9
Fiorentina
113
Fiorentina
10
Lazio
16
Lazio
11
Athletic Club de Bilbao
62
Athletic Club de Bilbao
12
RCD Espanyol
92
RCD Espanyol
13
FC Girondins de Bordeaux
86
FC Girondins de Bordeaux
14
Stade Rennais FC
146
Stade Rennais FC
15
SV Werder Bremen
28
SV Werder Bremen
16
Udinese
137
Udinese
17
Getafe CF
42
Getafe CF
18
VfL Wolfsburg
40
VfL Wolfsburg
19
Olympique de Marseille
45
Olympique de Marseille
20
Olympique Lyonnais
19
Olympique Lyonnais
21
Leicester City
50
Leicester City
22
Paris Saint-Germain
2
Paris Saint-Germain

In [40]:
tier6_teams = ranking_df[ranking_df['Tier']==6]

tier6_teams = tier6_teams.reset_index()

tier6_teams = tier6_teams.drop(['index'],axis=1)

for i in range(0,len(tier6_teams)):
    print(i)
    print(tier6_teams.iloc[i]['Team'])
    for j in range(0,len(dataset_teams)):
        if (tier6_teams.iloc[i]['Team'] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
Borussia Mönchengladbach
34
Borussia Mönchengladbach
1
Atalanta
23
Atalanta
2
Newcastle United
97
Newcastle United
3
AZ Alkmaar
174
AZ Alkmaar
4
Feyenoord
110
Feyenoord
5
SC Heerenveen
473
SC Heerenveen
6
FC Groningen
236
FC Groningen
7
Vitesse
297
Vitesse
8
FC Utrecht
201
FC Utrecht
9
FC Twente
374
FC Twente
10
Sampdoria
49
Sampdoria
11
LOSC Lille
87
LOSC Lille
12
Genoa
125
Genoa
13
AS Saint-Étienne
31
AS Saint-Étienne
14
OGC Nice
96
OGC Nice
15
Eintracht Frankfurt
44
Eintracht Frankfurt

In [41]:
tier7_teams = ranking_df[ranking_df['Tier']==7]

tier7_teams = tier7_teams.reset_index()

tier7_teams = tier7_teams.drop(['index'],axis=1)

for i in range(0,len(tier7_teams)):
    print(i)
    print(tier7_teams.iloc[i]['Team'])
    for j in range(0,len(dataset_teams)):
        if (tier7_teams.iloc[i]['Team'] in dataset_teams[j]):
            print(j)
            print(dataset_teams[j])

0
Crystal Palace
41
Crystal Palace
1
Bournemouth
79
Bournemouth
2
Brighton & Hove Albion
98
Brighton & Hove Albion
3
Burnley
118
Burnley
4
Norwich City
109
Norwich City
5
Sheffield United
202
Sheffield United
6
Watford
77
Watford
7
Wolverhampton Wanderers
30
Wolverhampton Wanderers
8
Granada CF
215
Granada CF
9
Levante UD
72
Levante UD
10
CA Osasuna
225
CA Osasuna
11
Deportivo Alavés
63
Deportivo Alavés
12
Real Valladolid CF
81
Real Valladolid CF
13
RCD Mallorca
271
RCD Mallorca
14
SD Eibar
101
SD Eibar
15
CD Leganés
130
CD Leganés
16
RB Leipzig
20
RB Leipzig
17
SC Paderborn 07
408
SC Paderborn 07
18
FC Augsburg
140
FC Augsburg
19
1. FC Köln
78
1. FC Köln
20
Fortuna Düsseldorf
172
Fortuna Düsseldorf
21
SC Freiburg
145
SC Freiburg
22
1. FSV Mainz 05
135
1. FSV Mainz 05
23
1. FC Union Berlin
187
1. FC Union Berlin
24
SPAL
169
SPAL
25
Bologna
159
Bologna
26
Brescia
67
Brescia
27
Cagliari
54
Cagliari
28
Lecce
261
Lecce
29
Parma
152
Parma
30
Sassuolo
85
Sassuolo
31
Hellas Verona
184
Hellas Verona
32
Amiens SC
183
Amiens SC
33
Angers SCO
139
Angers SCO
34
Stade Brestois 29
280
Stade Brestois 29
35
Dijon FCO
330
Dijon FCO
36
FC Metz
267
FC Metz
37
Montpellier HSC
75
Montpellier HSC
38
FC Nantes
94
FC Nantes
39
Nîmes Olympique
167
Nîmes Olympique
40
Stade de Reims
242
Stade de Reims
41
RC Strasbourg Alsace
121
RC Strasbourg Alsace
42
Toulouse Football Club
127
Toulouse Football Club
43
VVV-Venlo
427
VVV-Venlo
44
Heracles Almelo
470
Heracles Almelo
45
Sparta Rotterdam
572
Sparta Rotterdam
46
PEC Zwolle
477
PEC Zwolle
47
ADO Den Haag
441
ADO Den Haag
48
Fortuna Sittard
425
Fortuna Sittard
49
Willem II
462
Willem II
50
FC Emmen
486
FC Emmen
51
RKC Waalwijk
629
RKC Waalwijk